fragment ActionDetails on Action{
    id
    name

    ... on EmailAction {
        recipients
        subjectTemplate
        emailBodyTemplate: bodyTemplate
        useProxy
        labels
    }

    ... on HumioRepoAction {
        ingestToken
        labels
    }

    ... on OpsGenieAction {
        apiUrl
        genieKey
        useProxy
        labels
    }

    ... on PagerDutyAction {
        severity
        routingKey
        useProxy
        labels
    }

    ... on SlackAction {
        url
        fields {
            fieldName
            value
        }
        useProxy
        labels
    }

    ... on SlackPostMessageAction {
        apiToken
        channels
        fields {
            fieldName
            value
        }
        useProxy
        labels
    }

    ... on VictorOpsAction {
        messageType
        notifyUrl
        useProxy
        labels
    }

    ... on UploadFileAction {
        fileName
        labels
    }

    ... on WebhookAction {
        method
        url
        headers {
            header
            value
        }
        WebhookBodyTemplate: bodyTemplate
        ignoreSSL
        useProxy
        labels
    }

    ... on S3Action {
        roleArn
        awsRegion
        bucketName
        fileName
        outputFormat
        outputMetadata
        useProxy
        labels
    }
}

fragment ActionDetailsWithoutS3 on Action{
    id
    name

    ... on EmailAction {
        recipients
        subjectTemplate
        emailBodyTemplate: bodyTemplate
        useProxy
        labels
    }

    ... on HumioRepoAction {
        ingestToken
        labels
    }

    ... on OpsGenieAction {
        apiUrl
        genieKey
        useProxy
        labels
    }

    ... on PagerDutyAction {
        severity
        routingKey
        useProxy
        labels
    }

    ... on SlackAction {
        url
        fields {
            fieldName
            value
        }
        useProxy
        labels
    }

    ... on SlackPostMessageAction {
        apiToken
        channels
        fields {
            fieldName
            value
        }
        useProxy
        labels
    }

    ... on VictorOpsAction {
        messageType
        notifyUrl
        useProxy
        labels
    }

    ... on UploadFileAction {
        fileName
        labels
    }

    ... on WebhookAction {
        method
        url
        headers {
            header
            value
        }
        WebhookBodyTemplate: bodyTemplate
        ignoreSSL
        useProxy
        labels
    }
}

query ListActions(
    $SearchDomainName: String!
) {
    searchDomain(
        name: $SearchDomainName
    ) {
        actions {
            ...ActionDetails
        }
    }
}

query ListActionsWithoutS3(
    $SearchDomainName: String!
) {
    searchDomain(
        name: $SearchDomainName
    ) {
        actions {
            ...ActionDetailsWithoutS3
        }
    }
}

query GetActionByID(
    $SearchDomainName: String!
    $ActionID: String!
) {
    searchDomain(
        name: $SearchDomainName
    ) {
        action(
            id: $ActionID
        ) {
            ...ActionDetails
        }
    }
}

mutation DeleteActionByID(
    $SearchDomainName: String!
    $ActionID: String!
) {
    deleteAction(input: {
        viewName: $SearchDomainName
        id: $ActionID
    })
}

mutation CreateEmailAction(
    $SearchDomainName: String!
    $ActionName: String!
    $Recipients: [String!]!
    $SubjectTemplate: String
    $BodyTemplate: String
    $UseProxy: Boolean!
    $Labels: [String!]
) {
    createEmailAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        recipients: $Recipients
        subjectTemplate: $SubjectTemplate
        bodyTemplate: $BodyTemplate
        useProxy: $UseProxy
        labels: $Labels
    }) {
        id
        name
        recipients
        subjectTemplate
        bodyTemplate
        useProxy
        labels
    }
}

mutation CreateHumioRepoAction(
    $SearchDomainName: String!
    $ActionName: String!
    $IngestToken: String!
    $Labels: [String!]
) {
    createHumioRepoAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        ingestToken: $IngestToken
        labels: $Labels
    }) {
        id
        name
        ingestToken
        labels
    }
}

mutation CreateOpsGenieAction(
    $SearchDomainName: String!
    $ActionName: String!
    $ApiUrl: String!
    $GenieKey: String!
    $UseProxy: Boolean!
    $Labels: [String!]
) {
    createOpsGenieAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        apiUrl: $ApiUrl
        genieKey: $GenieKey
        useProxy: $UseProxy
        labels: $Labels
    }) {
        id
        name
        apiUrl
        genieKey
        useProxy
        labels
    }
}

mutation CreatePagerDutyAction(
    $SearchDomainName: String!
    $ActionName: String!
    $Severity: String!
    $RoutingKey: String!
    $UseProxy: Boolean!
    $Labels: [String!]
) {
    createPagerDutyAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        severity: $Severity
        routingKey: $RoutingKey
        useProxy: $UseProxy
        labels: $Labels
    }) {
        id
        name
        severity
        routingKey
        useProxy
        labels
    }
}

mutation CreateSlackAction(
    $SearchDomainName: String!
    $ActionName: String!
    $Fields: [SlackFieldEntryInput!]!
    $Url: String!
    $UseProxy: Boolean!
    $Labels: [String!]
) {
    createSlackAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        fields: $Fields
        url: $Url
        useProxy: $UseProxy
        labels: $Labels
    }) {
        id
        name
        fields {
            value
            fieldName
        }
        url
        useProxy
        labels
    }
}

mutation CreateSlackPostMessageAction(
    $SearchDomainName: String!
    $ActionName: String!
    $ApiToken: String!
    $Channels: [String!]!
    $Fields: [SlackFieldEntryInput!]!
    $UseProxy: Boolean!
    $Labels: [String!]
) {
    createSlackPostMessageAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        apiToken: $ApiToken
        channels: $Channels
        fields: $Fields
        useProxy: $UseProxy
        labels: $Labels
    }) {
        id
        name
        apiToken
        channels
        fields {
            value
            fieldName
        }
        useProxy
        labels
    }
}

mutation CreateVictorOpsAction(
    $SearchDomainName: String!
    $ActionName: String!
    $MessageType: String!
    $NotifyUrl: String!
    $UseProxy: Boolean!
    $Labels: [String!]
) {
    createVictorOpsAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        messageType: $MessageType
        notifyUrl: $NotifyUrl
        useProxy: $UseProxy
        labels: $Labels
    }) {
        id
        name
        messageType
        notifyUrl
        useProxy
        labels
    }
}

mutation CreateUploadFileAction(
    $SearchDomainName: String!
    $ActionName: String!
    $FileName: String!
    $Labels: [String!]
) {
    createUploadFileAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        fileName: $FileName
        labels: $Labels
    }) {
        id
        name
        fileName
        labels
    }
}

mutation CreateWebhookAction(
    $SearchDomainName: String!
    $ActionName: String!
    $Url: String!
    $Method: String!
    $Headers: [HttpHeaderEntryInput!]!
    $BodyTemplate: String!
    $IgnoreSSL: Boolean!
    $UseProxy: Boolean!
    $Labels: [String!]
) {
    createWebhookAction(input: {
        viewName: $SearchDomainName
        name: $ActionName
        url: $Url
        method: $Method
        headers: $Headers
        bodyTemplate: $BodyTemplate
        ignoreSSL: $IgnoreSSL
        useProxy: $UseProxy
        labels: $Labels
    }) {
        id
        name
        url
        method
        headers {
            value
            header
        }
        bodyTemplate
        ignoreSSL
        useProxy
        labels
    }
}

mutation CreateS3Action(
    $SearchDomainName: RepoOrViewName!
    $ActionName: String!
    $RoleArn: String!
    $AwsRegion: String!
    $BucketName: String!
    $FileName: String!
    $OutputFormat: S3ActionEventOutputFormat!
    $OutputMetadata: Boolean!
    $UseProxy: Boolean!
    $Labels: [String!]
) {
    createS3Action(input: {
        viewName: $SearchDomainName
        name: $ActionName
        roleArn: $RoleArn
        awsRegion: $AwsRegion
        bucketName: $BucketName
        fileName: $FileName
        outputFormat: $OutputFormat
        outputMetadata: $OutputMetadata
        useProxy: $UseProxy
        labels: $Labels
    }) {
        id
        name
        roleArn
        awsRegion
        bucketName
        fileName
        outputFormat
        outputMetadata
        useProxy
        labels
    }
}
